### ISSUE TITLE
Add `humans.txt`

### ISSUE THREAD

**Issue by willdurand** [TailorDev/monod#124]
There are a few 404 on ELK, so I guess people want this file :)

**Comment by hkasera** [comment]
@willdurand Can I take this up? If yes, please let me know the contributors to add!

**Comment by willdurand** [comment]
@hkasera yes, sure! As for the contributors, I'd say "TailorDev and awesome contributors", sounds good to you?

**Comment by willdurand** [comment]
Hi @hkasera, is there anything I can do to help you with this issue?

**Comment by prayashm** [comment]
Is it okay if I complete @stevensona's PR?

**Comment by willdurand** [comment]
@prayashm yes of course!
