### ISSUE TITLE
Typing and erasing some text does not update the rendered view

### ISSUE THREAD

**Issue by gchudnov** [TailorDev/monod#125]
1. Open https://monod.lelab.tailordev.fr
2. Type some text
3. Erase it

There should be some leftover characters on the rendered view.
Chrome 50,
Firefox 47.0a2 (2016-04-19)

**Comment by jmaupetit** [comment]
As for #127 I think it's a Preview component update issue, but i cannot reproduce it.

**Comment by willdurand** [comment]
I can reproduce this bug too.. I

**Comment by willdurand** [comment]
Found the root cause. Should be fixed now.

**Comment by gchudnov** [comment]
Thank you!

**Comment by willdurand** [comment]
Thank you for reporting the issue!
