### ISSUE TITLE
Can support save file to local storage?

### ISSUE THREAD

**Issue by swinghu** [TailorDev/monod#126]
Can support save file to local storage?
Hi , will Monod will support save file to local storage?  I  have tried Monod , however did not found it .

**Comment by willdurand** [comment]
Hi! What do you mean exactly? The choice of the client-side persistence layer is left to [localForage](https://github.com/mozilla/localForage), which decides the best storage to use depending on the browser.

**Comment by swinghu** [comment]
Thanks for you reply, what I want to know is that whether Monod will  supply a "save" button, which user can open a directory to save the document where he or she want to save.

**Comment by willdurand** [comment]
Hey @swinghu, do you want to save the Markdown content of a Monod document?

**Comment by jmaupetit** [comment]
Should be linked to #195

**Comment by willdurand** [comment]
no answer for 6 months, closing. You can save markdown content with the `[cmd] + s` shortcut on the left panel 😉
