### ISSUE TITLE
Semicolons seem to have an escape issue

### ISSUE THREAD

**Issue by seryl** [TailorDev/monod#127]
When editing the left panel (class: `CodeMirror-lines`), it appears that semicolons need to be escaped manually for it to appear on the right side.

Ex:

Change

```
> **TL;DR** Monod is a
```

to

```
> **T;DR** Monod is a
```

And then back

```
> **TL;DR** Monod is a
```

you'll see the L is never rendered.

However, if you escape it; things work as intended.

```
> **TL\;DR** Monod is a
```

**Comment by jmaupetit** [comment]
Hi @seryl, thank you for your feedback! I can reproduce this behavior, but it's not directly related to semicolons: instead of escaping the semicolon, type any character and the preview will update as expected. The Preview component is not updated as it should be.

**Comment by willdurand** [comment]
I reproduce this bug too..
