### ISSUE TITLE
Ignore partial BibTeX reference parsing errors

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/monod#185]
Current `cite` markdown-it plugin implementation does not support partial references like:

```
@article{bowie1969,
  title={Space Oddity}
}
```

This reference parsing raises an error, freezing the preview rendering. We need to ignore those errors to allow references "manual" edition (instead of full reference copy/paste).

**Comment by willdurand** [comment]
👍 I fixed the issue locally

**Comment by willdurand** [comment]
https://app.getsentry.com/tailordev-oss/monod/issues/153495644/

**Comment by willdurand** [comment]
https://app.getsentry.com/tailordev-oss/monod/issues/153495363/

**Comment by willdurand** [comment]
https://app.getsentry.com/tailordev-oss/monod/issues/153496660/
