### ISSUE TITLE
(Native) English proofreading

### ISSUE THREAD

**Issue by willdurand** [TailorDev/monod#227]
Hi!

As non-native English speakers/writers, we are looking for people willing to proofread the documentation: https://github.com/TailorDev/monod/tree/master/doc.

Thank you for your help ❤️

**Comment by gar** [comment]
I'd be willing to look at this. Is it only the `writing.md` and `templates.md` files that need to be proofread?

**Comment by willdurand** [comment]
Hi @gar! These two files are the most read I guess, but the `README` and `CONTRIBUTING` file could be checked too. As for the "code", we store all our text entries in this [`config.js` file](https://github.com/TailorDev/monod/blob/master/app/config.js). It is up to you to proofread it too. Thank you so much!

**Comment by codeahead14** [comment]
I believe I have a good command over English and can help you guys to proofread the documentation.

**Comment by gar** [comment]
Thanks @willdurand, I'll begin looking at that and I'll open a PR. @codeahead14 maybe I could ping you to review the PR when I have it done?

**Comment by codeahead14** [comment]
@gar Actually I had started working on the Writing.md file and made some suitable changes. I subsequently opened a PR but I doubt it was accepted. You could check the same at the link referenced by @willdurand .

**Comment by willdurand** [comment]
> @gar Actually I had started working on the Writing.md file and made some suitable changes. I subsequently opened a PR but I doubt it was accepted. You could check the same at the link referenced by @willdurand .

@codeahead14 thank you for having reviewed the `writing` file. Hopefully @gar will review your changes, and then we will merge your very first PR! Yet, @gar raised his hand before, and therefore it would be nice to let him do the proofreading first, and then (as he suggested) you review his PR. Deal?

**Comment by cynicaldevil** [comment]
@willdurand I can take a look at the `CODE_OF_CONDUCT` file, if that's alright.

**Comment by milkey-mouse** [comment]
I can read over everything in a few days. I see a few places that could be improved.

**Comment by willdurand** [comment]
Hi @cynicaldevil, we did not write the CoC file ourselves, so it should be ok. Better report at: https://github.com/ContributorCovenant/contributor_covenant.

**Comment by gar** [comment]
@willdurand let me know your thoughts on the above pull-request. I made some changes to `app/config.js` as well, but all the tests are passing.

**Comment by willdurand** [comment]
@gar thanks; just reviewed the PR

**Comment by willdurand** [comment]
Done, thanks everyone!
