### ISSUE TITLE
Update eslint-plugin-import to version 2.0.0

### ISSUE THREAD

**Issue by willdurand** [TailorDev/monod#233]
According to [this PR](https://github.com/TailorDev/monod/pull/232), this new version breaks the build (see [build status 755](https://circleci.com/gh/TailorDev/monod/755) too). We need to understand why it fails, and how to fix it.

**Comment by finalfreq** [comment]
I can take a look into this

**Comment by finalfreq** [comment]
Looks like with the update there were missing dependencies, which I have taken care of in PR, problem i'm now seeing is it is linting but its saying previously ok imports are being flagged as bad. Will dig deeper into that issue [build status 759](https://circleci.com/gh/TailorDev/monod/759)

**Comment by finalfreq** [comment]
It looks like eslint-config-airbnb is set to eslint-plugin-import@^1.16.0 in its peer dependencies. I'm not entirely familiar with how npm handles version differences between dependencies. Do you know if this can only be resolved once that library has updated its version as well?

**Comment by willdurand** [comment]
> Do you know if this can only be resolved once that library has updated its version as well?

Yes, I think so..
