### ISSUE TITLE
Make keyboard shortcuts available for everyone!

### ISSUE THREAD

**Issue by willdurand** [TailorDev/monod#249]
## Purpose

Monod supports keyboard shortcuts like `Cmd + S`, etc. Yet, it only supports `Cmd` (the MacOS key), which is more or less like `Ctrl` on other OS. This should be changed to support every OS/keyboard.

## Proposal

Here is some code from CodeMirror to decide whether to use `Cmd` or `Ctrl`:

```
var mac = CodeMirror.keyMap["default"] == CodeMirror.keyMap.macDefault;
var ctrl = mac ? "Cmd-" : "Ctrl-";
```

It should be possible to reuse this snippet in [`extra-keys.js`](https://github.com/TailorDev/monod/blob/master/app/components/Markdown/extra-keys.js) to automatically use the right prefix.

**Comment by tmpace** [comment]
I'd like to work on this!

**Comment by willdurand** [comment]
Hi @tmpace, then you are assigned! (virtually)

**Comment by kytwb** [comment]
@tmpace I forgot to claim the issue and was already working on it :disappointed: Let me know if you need help or if you give it up, I already have a commit waiting to be PR'ed.
