### ISSUE TITLE
Make sure full screen button is visible in 1024 width (projector) 

### ISSUE THREAD

**Issue by willdurand** [TailorDev/monod#256]

**Comment by Kunamatata** [comment]
@willdurand Does this issue concern the presentation mode button if so does the title suggest keeping it visible underneath 1024 width ?

**Comment by willdurand** [comment]
Yes and yes.

It is the little "play" button (aka presentation mode button or fullscreen mode button).  If you downgrade your screen size, you'll notice that it disappears (for responsiveness purpose). Yet, we need it as most video projectors have a low resolution.

**Comment by Kunamatata** [comment]
Perfect ! I'll get on this, I wanted to make sure we were talking about the same button.

**Comment by willdurand** [comment]
fixed now, and deployed!
